package org.example.androidsdk.hackathon.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FRIEND".
 */
public class Friend {

    private String name;
    private String fbId;
    private Boolean isAdded;

    public Friend() {
    }

    public Friend(String name, String fbId, Boolean isAdded) {
        this.name = name;
        this.fbId = fbId;
        this.isAdded = isAdded;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFbId() {
        return fbId;
    }

    public void setFbId(String fbId) {
        this.fbId = fbId;
    }

    public Boolean getIsAdded() {
        return isAdded;
    }

    public void setIsAdded(Boolean isAdded) {
        this.isAdded = isAdded;
    }

}
